FROM node:20.18-alpine

RUN apk add git
RUN git clone https://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@github.com/alexandermamaniyucra/ccp-hotel-coupon-frontend.git

RUN useradd -m hoteluser

WORKDIR /ccp-hotel-coupon-frontend

RUN npm install --force
RUN npm run build

RUN mkdir -p  /hotelcoupon/static
RUN cp -r dist/* /hotelcoupon/static/

RUN chmod -R 775 /ccp-hotel-coupon-backend/static
RUN chown -R hoteluser:hoteluser /ccp-hotel-coupon-backend/static
