version: '3.8'

services:
  web:
    build:
      context: "$PWD"
      dockerfile: Dockerfile.staging
    command: >
      sh -c "
          python -m gunicorn --workers 3 --bind 0.0.0.0:8000 --timeout 120  hotelcoupon.wsgi:application"
    container_name: hotel-app-web-service
    ports:
      - "8000:8000"
    networks:
      - network_main_net
    restart: always
    env_file: .env.staging
    volumes:
      - .:/hotelcoupon
      - /hotelcoupon/__pycache__/
  nginx:
    build:
      context: "$PWD"
      dockerfile: Dockerfile-nginx.staging
    container_name: hotel-app-gui
    command: >
      sh -c "
          nginx -g 'daemon off;'"
    restart: always
    networks:
      - network_main_net
    ports:
      - "3000:80"
    depends_on:
      - web
networks:
  network_main_net:
    name: network_main_net

