# Generated by Django 4.2.14 on 2024-11-14 23:21

import coupons.models
from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('deleted_date', models.DateTimeField(blank=True, null=True, verbose_name='Deleted date')),
                ('is_active', models.BooleanField(default=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('discount', models.PositiveIntegerField(default=0, verbose_name='Discount')),
                ('media_url', models.ImageField(blank=True, null=True, upload_to=coupons.models.upload_to)),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='Quantity')),
                ('how_many_have_redeemed', models.PositiveIntegerField(default=0, verbose_name='How many coupons have been redemeed')),
                ('how_many_have_used', models.PositiveIntegerField(default=0, verbose_name='How many coupons have been used')),
                ('expiration_date', models.DateTimeField(blank=True, null=True, verbose_name='Expiration date')),
            ],
            options={
                'verbose_name': 'Coupon',
                'verbose_name_plural': 'Coupons',
                'ordering': ['title'],
            },
        ),
    ]
