# Generated by Django 4.2.14 on 2024-11-07 13:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('coupons', '0001_initial'),
        ('hotelier_profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='hotelier_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotelier_profiles.hotelierprofile', verbose_name='Hotelier profile'),
        ),
    ]
