# Generated by Django 4.2.14 on 2024-11-15 00:47

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import reports.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hotelier_profiles', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('deleted_date', models.DateTimeField(blank=True, null=True, verbose_name='Deleted date')),
                ('is_active', models.BooleanField(default=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('media_url', models.ImageField(blank=True, null=True, upload_to=reports.models.upload_to)),
                ('hotelier_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotelier_profiles.hotelierprofile', verbose_name='Hotelier profile')),
            ],
            options={
                'verbose_name': 'Report',
                'verbose_name_plural': 'Reports',
                'ordering': ['title'],
            },
        ),
    ]
