# Generated by Django 4.2.14 on 2024-11-14 23:21

from django.db import migrations, models
import django.utils.timezone
import hotelier_profiles.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HotelierProfile',
            fields=[
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('deleted_date', models.DateTimeField(blank=True, null=True, verbose_name='Deleted date')),
                ('is_active', models.BooleanField(default=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255, verbose_name='Hotel Name')),
                ('telephone', models.CharField(blank=True, max_length=255, verbose_name='Hotel Telephone')),
                ('country', models.CharField(blank=True, max_length=255, verbose_name='Hotel Country')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='Hotel Address')),
                ('picture_url', models.ImageField(blank=True, null=True, upload_to=hotelier_profiles.models.upload_to)),
            ],
            options={
                'verbose_name': 'Hotelier Profile',
                'verbose_name_plural': 'Hotelier Profiles',
                'ordering': ['name'],
            },
        ),
    ]
