# Generated by Django 4.2.14 on 2024-11-07 13:58

from django.db import migrations, models
import django.utils.timezone
import user_profiles.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('coupons', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('deleted_date', models.DateTimeField(blank=True, null=True, verbose_name='Deleted date')),
                ('is_active', models.BooleanField(default=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('full_name', models.CharField(blank=True, max_length=255, verbose_name='Full name')),
                ('picture_url', models.ImageField(blank=True, null=True, upload_to=user_profiles.models.upload_to)),
                ('coupons', models.ManyToManyField(related_name='profiles', to='coupons.coupon')),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
                'ordering': ['full_name'],
            },
        ),
    ]
